# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: twcb-appengine
  CLOUD_SQL_PASSWORD: test123
  CLOUD_SQL_DATABASE_NAME: thirdwavecoffeebase
  CLOUD_SQL_CONNECTION_NAME: third-wave-coffee-base:us-west2:thirdwavecoffeebase
# [END gae_python37_cloudsql_config]
